---
kind: pipeline
name: packer-ops-httpd
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
- name: validate
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/dq-packer-ansible
  commands:
  - export HOME=/home/packer
  - packer validate packer.json

- name: inspect
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/dq-packer-ansible
  commands:
  - export HOME=/home/packer
  - packer inspect packer.json

- name: build
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/dq-packer-ansible
  commands:
  - export HOME=/home/packer
  - export aws_access_key_id=$${AWS_ACCESS_KEY_ID}
  - export aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}
  - packer build packer.json
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: CI_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: CI_SECRET_ACCESS_KEY
    RHUSERNAME:
      from_secret: RHUSERNAME
    RHPASSWORD:
      from_secret: RHPASSWORD
  when:
    event:
    - push

# - name: packer-copy-notprod
#   pull: always
#   image: quay.io/ukhomeofficedigital/dq-packer-encrypt-copy
#   commands:
#   - export filters="--owner 093401982388 --filters "Name=name,Values=dq-ops-httpd*""
#   - export aws_id=$$NOTPROD_ACC_ID
#   - export aws_key=$$NOTPROD_ACC_KEY
#   - export region=eu-west-2
#   - export HOME=/home/packer
#   - cd /home/packer
#   - ./build.sh
#   environment:
#     NOTPROD_ACC_ID:
#       from_secret: NOTPROD_ACC_ID
#     NOTPROD_ACC_KEY:
#       from_secret: NOTPROD_ACC_KEY
#   when:
#     event:
#     - push

# - name: packer-copy-prod
#   pull: always
#   image: quay.io/ukhomeofficedigital/dq-packer-encrypt-copy
#   commands:
#   - export filters="--owner 093401982388 --filters "Name=name,Values=dq-ops-httpd*""
#   - export aws_id=$$PROD_ACC_ID
#   - export aws_key=$$PROD_ACC_KEY
#   - export region=eu-west-2
#   - export HOME=/home/packer
#   - cd /home/packer
#   - ./build.sh
#   environment:
#     PROD_ACC_ID:
#       from_secret: PROD_ACC_ID
#     PROD_ACC_KEY:
#       from_secret: PROD_ACC_KEY
#   when:
#     branch:
#     - master
#     event:
#     - push

...
