vars_files:
    - ./vars/dqusers.yml
  tasks:
  - name: Create users for dqsupport members
      user:
          name: "{{ item.name }}"
          shell: /bin/bash
          createhome: yes                    
      with_items: "{{ dqusers }}"      

  - name: setup ssh pub key for abv defined users  
      authorized_key:
        user: '{{ item.name }}'
        state: present
        key: '{{ item.pubkey }}'
      with_items: "{{ dqusers }}"     

  - name: deploy sudoers file
      template:
        src: dqsupport-sudoers.j2
        dest: /etc/sudoers.d/{{ item.userno }}-{{ item.name }}-user
      with_items:
      - "{{ dqusers }}" 
      become: true
      become_user: root
